language: python
sudo: false

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - ldap-utils
      - slapd

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.3"
      env: TOXENV=py33
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
install:
  - pip install "pip>=7.1.0"
  - pip install tox

script: tox
